# Weaver project config: https://github.com/open-telemetry/weaver
[registry]
path = "model"
v2 = true

[policy]
paths = ["https://github.com/open-telemetry/opentelemetry-weaver-packages.git@cd596eae86e732158bc89c4f4c47d07a97e9ab34[policies/check/naming_conventions]"]

[template]
acronyms = ["HTTP", "URL", "ID", "API", "GC"]

[template.text_maps.upstream_docs]
"https://opentelemetry.io/schemas/1.44.0" = "https://github.com/open-telemetry/semantic-conventions/blob/v1.44.0/docs/registry/attributes/{namespace}.md"
