version: "3"

tasks:
  fmt:
    desc: Format Go source files
    cmds:
      - gofumpt -w .

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  test:
    desc: Run tests
    cmds:
      - go test -race ./...

  tidy:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  check:
    desc: Run fmt, vet, lint, and test
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test
