// Code generated by weaver from model/. DO NOT EDIT.

// Package semconv holds the attribute keys and metric names defined in
// this module's telemetry registry (model/).
package semconv

import "go.opentelemetry.io/otel/attribute"

// Attributes.
const (
	// HTTP status code carried by the problem details.
	ProblemStatusKey = attribute.Key("problem.status")
	// RFC 9457 problem type URI of an error response.
	//
	// `unclassified` when the error response did not go through `problem.Write`.
	ProblemTypeKey = attribute.Key("problem.type")
)

// ProblemStatus returns a problem.status attribute.
func ProblemStatus(val int) attribute.KeyValue {
	return ProblemStatusKey.Int(val)
}

// ProblemType returns a problem.type attribute.
func ProblemType(val string) attribute.KeyValue {
	return ProblemTypeKey.String(val)
}

// servicepack.http.server.problems (counter).
const (
	ServicepackHTTPServerProblemsName        = "servicepack.http.server.problems"
	ServicepackHTTPServerProblemsUnit        = "{problem}"
	ServicepackHTTPServerProblemsDescription = "Number of HTTP server error responses (status 400 and above)."
)
